### ISSUE TITLE
Merge MiTools to MiLib ?

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mitools#5]
What do you think guys?

**Comment by dbolotin** [comment]
Maybe merge everything except CLI to MiLib....

**Comment by mikessh** [comment]
How about versioning? I would prefer rare stable releases from Milib and more Mitools releases with new features added for purposes of our ongoing projects. Things like
```
<dependency>
            <groupId>com.milaboratory</groupId>
            <artifactId>milib</artifactId>
            <version>${project.version}</version>
</dependency>
```
are a bit annoying for me.
